# Generated by Django 4.1.1 on 2022-09-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_url',
            field=models.URLField(default='no image available'),
        ),
    ]
